list = [1, 5, 7, 9, 5, 9, 5, 1, 6, 6, 10, 38, 2]
print(list)
print(list.index(5))
print(max(list))
print(min(list))
print(list.count(5))
list.reverse()
print(list)
list.sort()
print(list)
print("")
list_new1 = list.copy()
print(list_new1)

list_new2 = list
print(list_new2)
print("")
list.remove(10)
print(list)
print(list_new1)
print(list_new2)
print("")
list_new2.clear()
print(list)
print(list_new1)
print(list_new2)
