vari1 = int(input("Number 1 of 6 "))
vari2 = int(input("Number 1 of 6 "))
vari3 = int(input("Number 1 of 6 "))
vari4 = int(input("Number 1 of 6 "))
vari5 = int(input("Number 1 of 6 "))
vari6 = int(input("Number 1 of 6 "))
vari7 = int(input("Number 1 of 6 "))
