quent1_input = input("please give me any number")
quent2_input = input("please add the number by one")
quent3_input = input("multiply the number by two")
quent4_input = input("divide the number by three")
quent5_input = input(" subtract the number by one")
quent6_input = input("add the number by six")
quent7_input = input("do integer division with the number")
quent8_input = input("please power the number")
quent9_input = input("please make the number bigger")
quent10_input = input("please make the number smaller than its self")

print(quent1_input)
print(quent2_input)
print(quent3_input)
print(quent4_input)
print(quent5_input)
print(quent6_input)
print(quent7_input)
print(quent8_input)
print(quent9_input)
print(quent10_input)
